import test, { after } from 'node:test'
import assert from 'node:assert/strict'
import request from 'supertest'

process.env.NODE_ENV = 'test'
const { app, pool } = await import('./index.js')

let token
test('catálogo reconciliado contém as 460 funções autenticadas',async()=>{
  const {moduleCatalog,slugify}=await import('../src/moduleCatalog.js')
  const expected={'Fiéis e Cadastros':30,'Dízimos e Ofertas':14,Financeiro:82,Batismo:22,Catequese:26,Crisma:23,Eucaristia:16,Matrimônio:39,Campanhas:10,'Agendas e Cursos':27,Almoxarifado:23,Cemitério:7,Contábil:61,Patrimônio:26,'Gestão Social':20,ParóquiaNet:8,Conectividade:4,'Partilha Fraterna':5,Configurações:17}
  const counts=Object.fromEntries(Object.entries(moduleCatalog).map(([name,module])=>[name,module.groups.flatMap(group=>group.items).length]))
  assert.deepEqual(counts,expected)
  assert.equal(Object.values(counts).reduce((sum,count)=>sum+count,0),460)
  const routes=[]
  for(const module of Object.values(moduleCatalog)){const labels=module.groups.flatMap(group=>group.items),duplicates=labels.reduce((all,label)=>({...all,[label]:(all[label]||0)+1}),{});module.groups.forEach((group,groupIndex)=>group.items.forEach((label,itemIndex)=>routes.push(`${module.slug}/${duplicates[label]>1?`${slugify(label)}-${groupIndex+1}-${itemIndex+1}`:slugify(label)}`)))}
  assert.equal(new Set(routes).size,460)
})
test('autentica o administrador local', async () => {
  const response = await request(app).post('/api/auth/login').send({ email:'admin@nucleo.local',password:'admin123' })
  assert.equal(response.status,200)
  assert.ok(response.body.token)
  token=response.body.token
})

test('as 460 funções possuem rota isolada e autorizada',async()=>{
  const {moduleCatalog,slugify}=await import('../src/moduleCatalog.js')
  for(const module of Object.values(moduleCatalog)){const labels=module.groups.flatMap(group=>group.items),duplicates=labels.reduce((all,label)=>({...all,[label]:(all[label]||0)+1}),{});for(const[groupIndex,group]of module.groups.entries())for(const[itemIndex,label]of group.items.entries()){const resource=duplicates[label]>1?`${slugify(label)}-${groupIndex+1}-${itemIndex+1}`:slugify(label),response=await request(app).get(`/api/registry/${module.slug}/${resource}`).set('Authorization',`Bearer ${token}`);assert.equal(response.status,200,`${module.slug}/${resource}`)}}
})

test('gestão de dados adiciona, edita e exclui em todas as áreas',async()=>{
  const modules=['fieis-cadastros','dizimos-ofertas','financeiro','batismo','catequese','crisma','eucaristia','matrimonio','campanhas','agenda-cursos','almoxarifado','cemiterio','contabil','patrimonio','gestao-social','paroquianet','conectividade','partilha-fraterna','configuracoes','documentos']
  for(const module of modules){const catalog=await request(app).get('/api/data-management/catalog').query({module}).set('Authorization',`Bearer ${token}`);assert.equal(catalog.status,200,module);assert.ok(catalog.body.entities.length,module);const list=await request(app).get(`/api/data-management/${catalog.body.entities[0].key}`).set('Authorization',`Bearer ${token}`);assert.equal(list.status,200,catalog.body.entities[0].key);assert.ok(Array.isArray(list.body.columns));assert.ok(Array.isArray(list.body.rows))}
  const stamp=Date.now(),entity='fieis-cadastros--parish_communities'
  const created=await request(app).post(`/api/data-management/${entity}`).set('Authorization',`Bearer ${token}`).send({values:{name:`Comunidade CRUD ${stamp}`,patron:'São Teste',active:true}})
  assert.equal(created.status,201,JSON.stringify(created.body))
  const edited=await request(app).patch(`/api/data-management/${entity}/${created.body.data.id}`).set('Authorization',`Bearer ${token}`).send({changes:{name:`Comunidade CRUD editada ${stamp}`,phone:'91999999999'}})
  assert.equal(edited.status,200,JSON.stringify(edited.body))
  assert.match(edited.body.data.name,/editada/)
  const removed=await request(app).delete(`/api/data-management/${entity}/${created.body.data.id}`).set('Authorization',`Bearer ${token}`)
  assert.equal(removed.status,200,JSON.stringify(removed.body))
  assert.equal(removed.body.mode,'deactivate')
  const hardEntity='agenda-cursos--tomb_book_entries',hard=await request(app).post(`/api/data-management/${hardEntity}`).set('Authorization',`Bearer ${token}`).send({values:{entry_date:'2096-01-01',title:`Tombo CRUD ${stamp}`,content:'Registro temporário',category:'Teste'}})
  assert.equal(hard.status,201,JSON.stringify(hard.body))
  const hardDeleted=await request(app).delete(`/api/data-management/${hardEntity}/${hard.body.data.id}`).set('Authorization',`Bearer ${token}`)
  assert.equal(hardDeleted.status,200,JSON.stringify(hardDeleted.body))
  assert.equal(hardDeleted.body.mode,'delete')
})

test('cria, consulta e arquiva registro operacional com escopo', async () => {
  const title=`Teste automatizado ${Date.now()}`
  const created=await request(app).post('/api/registry/patrimonio/inventario').set('Authorization',`Bearer ${token}`).send({title,status:'active',amount:100,data:{tombo:'QA-001',localizacao:'Sala de testes'}})
  assert.equal(created.status,201)
  assert.equal(created.body.data.title,title)

  const listed=await request(app).get('/api/registry/patrimonio/inventario').query({search:title}).set('Authorization',`Bearer ${token}`)
  assert.equal(listed.status,200)
  assert.equal(listed.body.data.length,1)

  const archived=await request(app).delete(`/api/registry/patrimonio/inventario/${created.body.data.id}`).set('Authorization',`Bearer ${token}`)
  assert.equal(archived.status,204)
})

test('emite PDF com código público de validação', async () => {
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const issued=await request(app).post('/api/documents/issue').set('Authorization',`Bearer ${token}`).send({templateCode:'generic-receipt',personId:people.body.data[0].id,values:{amount:'R$ 50,00',description:'teste automatizado',occurred_at:'20/08/2026'}})
  assert.equal(issued.status,201)
  const pdf=await request(app).get(`/api/documents/emissions/${issued.body.data.id}/pdf`).set('Authorization',`Bearer ${token}`)
  assert.equal(pdf.status,200)
  assert.equal(pdf.headers['content-type'],'application/pdf')
  assert.equal(Buffer.from(pdf.body).subarray(0,4).toString(),'%PDF')
  const validation=await request(app).get(`/api/documents/validate/${issued.body.data.validation_code}`)
  assert.equal(validation.status,200)
  assert.equal(validation.body.valid,true)
})

test('cria e liquida conta a pagar de forma transacional',async()=>{
  const metadata=await request(app).get('/api/finance/metadata').set('Authorization',`Bearer ${token}`)
  const payable=await request(app).post('/api/finance/obligations').set('Authorization',`Bearer ${token}`).send({type:'payable',description:`Conta QA ${Date.now()}`,categoryId:metadata.body.categories.find(item=>item.kind==='expense').id,costCenterId:metadata.body.costCenters[0].id,amount:125,dueDate:'2026-09-10'})
  assert.equal(payable.status,201)
  const settled=await request(app).post(`/api/finance/obligations/${payable.body.data.id}/settle`).set('Authorization',`Bearer ${token}`).send({accountId:metadata.body.accounts[0].id,amount:125,settlementDate:'2026-09-10',paymentMethod:'pix'})
  assert.equal(settled.status,201)
  assert.equal(settled.body.status,'settled')
  const obligations=await request(app).get('/api/finance/obligations?type=payable').set('Authorization',`Bearer ${token}`)
  assert.equal(obligations.body.data.find(item=>item.id===payable.body.data.id).status,'settled')
})

test('financeiro opera vales, cheques, repasses, recibos e orçamento',async()=>{
  const stamp=Date.now(),metadata=await request(app).get('/api/finance/metadata').set('Authorization',`Bearer ${token}`),people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  assert.ok(metadata.body.accounts.length>=2)
  const [fromAccount,toAccount]=metadata.body.accounts
  const voucher=await request(app).post('/api/finance/vouchers').set('Authorization',`Bearer ${token}`).send({voucherType:'advance',personId:people.body.data[0].id,beneficiaryName:people.body.data[0].name,description:`Adiantamento QA ${stamp}`,amount:120,issuedOn:'2090-01-02',dueOn:'2090-01-31'})
  assert.equal(voucher.status,201)
  assert.ok(voucher.body.data.obligation_id)
  const check=await request(app).post('/api/finance/checks').set('Authorization',`Bearer ${token}`).send({accountId:fromAccount.id,checkNumber:`CH-${stamp}`,payee:'Fornecedor QA',description:'Material',amount:80,issuedOn:'2090-01-03',dueOn:'2090-01-04'})
  assert.equal(check.status,201)
  const cleared=await request(app).post(`/api/finance/checks/${check.body.data.id}/clear`).set('Authorization',`Bearer ${token}`).send({clearedOn:'2090-01-04'})
  assert.equal(cleared.body.data.status,'cleared')
  assert.ok(cleared.body.data.financial_transaction_id)
  const transfer=await request(app).post('/api/finance/transfers').set('Authorization',`Bearer ${token}`).send({fromAccountId:fromAccount.id,toAccountId:toAccount.id,amount:50,transferredOn:'2090-01-05',description:'Reforço de caixa',reference:`TR-${stamp}`})
  assert.equal(transfer.status,201)
  assert.ok(transfer.body.data.outgoing_transaction_id)
  assert.ok(transfer.body.data.incoming_transaction_id)
  const receipt=await request(app).post('/api/finance/receipts').set('Authorization',`Bearer ${token}`).send({receiptType:'rpa',accountId:fromAccount.id,recipientName:'Prestador QA',recipientDocument:'12345678900',description:'Serviço eventual',grossAmount:200,deductionAmount:20,issuedOn:'2090-01-06',paymentMethod:'pix'})
  assert.equal(receipt.status,201)
  assert.equal(Number(receipt.body.data.net_amount),180)
  const structure=await request(app).post('/api/finance/budget-structures').set('Authorization',`Bearer ${token}`).send({code:`QA-${stamp}`,name:'Projeto pastoral QA',kind:'expense'})
  assert.equal(structure.status,201)
  const budget=await request(app).post('/api/finance/budgets').set('Authorization',`Bearer ${token}`).send({structureId:structure.body.data.id,year:2090,month:1,plannedAmount:1000})
  assert.equal(budget.status,201)
  const master=await request(app).post('/api/finance/master-data').set('Authorization',`Bearer ${token}`).send({dataType:'document_type',code:`DOC-${stamp}`,name:'Documento QA'})
  assert.equal(master.status,201)
  const overview=await request(app).get('/api/finance/operations?year=2090').set('Authorization',`Bearer ${token}`)
  assert.ok(overview.body.transfers.some(item=>item.id===transfer.body.data.id))
  assert.ok(overview.body.receipts.some(item=>item.id===receipt.body.data.id))
  assert.ok(overview.body.plans.some(item=>item.id===budget.body.data.id))
})

test('agenda celebração recorrente, intenção integrada e inscrição em curso',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const event=await request(app).post('/api/agenda/events').set('Authorization',`Bearer ${token}`).send({type:'mass',title:`Missa QA ${Date.now()}`,startsAt:'2026-10-04T12:00:00.000Z',endsAt:'2026-10-04T13:00:00.000Z',recurrence:'weekly',recurrenceCount:3,celebrant:'Pe. Teste'})
  assert.equal(event.status,201)
  assert.equal(event.body.occurrences.length,3)
  const metadata=await request(app).get('/api/agenda/intentions/metadata').set('Authorization',`Bearer ${token}`)
  const intention=await request(app).post('/api/agenda/intentions').set('Authorization',`Bearer ${token}`).send({eventId:event.body.data.id,intentionTypeId:metadata.body.types[0].id,requesterId:people.body.data[0].id,intentionFor:'Família de teste',amount:20,paymentMethod:'pix',status:'scheduled'})
  assert.equal(intention.status,201)
  assert.ok(intention.body.data.financial_transaction_id)
  const course=await request(app).post('/api/agenda/courses').set('Authorization',`Bearer ${token}`).send({name:`Formação QA ${Date.now()}`,capacity:1,status:'enrollment',fee:0})
  assert.equal(course.status,201)
  const enrollment=await request(app).post(`/api/agenda/courses/${course.body.data.id}/enrollments`).set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id})
  assert.equal(enrollment.status,201)
  assert.equal(enrollment.body.data.status,'enrolled')
})

test('cursos, campanhas e cemitério completam operações documentais',async()=>{
  const stamp=Date.now(),people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const course=await request(app).post('/api/agenda/courses').set('Authorization',`Bearer ${token}`).send({name:`Formação QA ${stamp}`,startsOn:'2093-01-01',endsOn:'2093-02-01',fee:50,status:'enrollment'})
  const enrollment=await request(app).post(`/api/agenda/courses/${course.body.data.id}/enrollments`).set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id})
  assert.equal(enrollment.status,201)
  assert.equal((await request(app).post(`/api/agenda/courses/${course.body.data.id}/advisors`).set('Authorization',`Bearer ${token}`).send({name:'Assessor QA',role:'Formador'})).status,201)
  const session=await request(app).post(`/api/agenda/courses/${course.body.data.id}/sessions`).set('Authorization',`Bearer ${token}`).send({title:'Encontro inicial',startsAt:'2093-01-05T12:00:00.000Z',endsAt:'2093-01-05T14:00:00.000Z',location:'Salão'})
  assert.equal(session.status,201)
  const checkin=await request(app).post(`/api/agenda/sessions/${session.body.data.id}/checkins`).set('Authorization',`Bearer ${token}`).send({enrollmentId:enrollment.body.data.id})
  assert.match(checkin.body.data.label_code,/^ETQ-/)
  assert.equal((await request(app).post(`/api/agenda/enrollments/${enrollment.body.data.id}/installments`).set('Authorization',`Bearer ${token}`).send({competence:'2093-01-01',dueDate:'2093-01-10',amount:50})).status,201)
  const certificate=await request(app).post(`/api/agenda/enrollments/${enrollment.body.data.id}/certificate`).set('Authorization',`Bearer ${token}`).send({issuedOn:'2093-02-01',workloadHours:20})
  assert.match(certificate.body.data.validation_code,/^[A-F0-9]+$/)
  assert.equal((await request(app).post('/api/agenda/contacts').set('Authorization',`Bearer ${token}`).send({name:'Contato QA',phoneType:'celular',phone:'91999999999'})).status,201)
  assert.equal((await request(app).post('/api/agenda/tomb-book').set('Authorization',`Bearer ${token}`).send({entryDate:'2093-02-02',title:'Marco pastoral QA',content:'Registro histórico automatizado.'})).status,201)
  const campaign=await request(app).post('/api/campaigns').set('Authorization',`Bearer ${token}`).send({name:`Campanha lote QA ${stamp}`,startsOn:'2093-01-01',targetAmount:1000,status:'active'})
  const pledge=await request(app).post(`/api/campaigns/${campaign.body.data.id}/pledges`).set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,amount:250,frequency:'once',pledgedOn:'2093-01-01',dueDate:'2093-01-31'})
  const batch=await request(app).post(`/api/campaigns/${campaign.body.data.id}/batches`).set('Authorization',`Bearer ${token}`).send({description:'Lote inicial QA',pledgeIds:[pledge.body.data.id]})
  assert.equal(Number(batch.body.data.total_amount),250)
  const emailed=await request(app).post(`/api/campaigns/batches/${batch.body.data.id}/email`).set('Authorization',`Bearer ${token}`).send({})
  assert.equal(emailed.body.data.status,'emailed')
  const graves=await request(app).get('/api/cemetery/graves').set('Authorization',`Bearer ${token}`),services=await request(app).get('/api/cemetery/services').set('Authorization',`Bearer ${token}`)
  const order=await request(app).post('/api/cemetery/service-orders').set('Authorization',`Bearer ${token}`).send({graveId:graves.body.data[0]?.id,serviceId:services.body.catalog[0].id,requesterId:people.body.data[0].id,requesterName:people.body.data[0].name,orderedOn:'2093-03-01',scheduledOn:'2093-03-02',amount:75,paymentMethod:'pix'})
  assert.equal(order.status,201)
  assert.ok(order.body.data.receipt_number)
  assert.ok(order.body.data.financial_transaction_id)
  assert.equal((await request(app).patch(`/api/cemetery/service-orders/${order.body.data.id}/status`).set('Authorization',`Bearer ${token}`).send({status:'completed'})).body.data.status,'completed')
  const operations=await request(app).get('/api/agenda/course-operations').set('Authorization',`Bearer ${token}`)
  assert.ok(operations.body.certificates.some(item=>item.id===certificate.body.data.id))
  assert.ok(operations.body.tombEntries.some(item=>item.title==='Marco pastoral QA'))
})

test('controla entrada, saída e impede estoque negativo',async()=>{
  const metadata=await request(app).get('/api/inventory/metadata').set('Authorization',`Bearer ${token}`)
  const product=await request(app).post('/api/inventory/products').set('Authorization',`Bearer ${token}`).send({sku:`QA-${Date.now()}`,name:'Vela de teste',unit:'un',minimumStock:5,categoryId:metadata.body.categories[0].id})
  assert.equal(product.status,201)
  const base={productId:product.body.data.id,locationId:metadata.body.locations[0].id,occurredAt:'2026-09-01'}
  const entry=await request(app).post('/api/inventory/movements').set('Authorization',`Bearer ${token}`).send({...base,kind:'entry',quantity:10,unitCost:2.5})
  assert.equal(entry.status,201)
  const exit=await request(app).post('/api/inventory/movements').set('Authorization',`Bearer ${token}`).send({...base,kind:'exit',quantity:4})
  assert.equal(exit.status,201)
  const rejected=await request(app).post('/api/inventory/movements').set('Authorization',`Bearer ${token}`).send({...base,kind:'exit',quantity:7})
  assert.equal(rejected.status,409)
  const products=await request(app).get('/api/inventory/products').set('Authorization',`Bearer ${token}`)
  assert.equal(Number(products.body.data.find(item=>item.id===product.body.data.id).stock),6)
})

test('almoxarifado processa requisição, compra, devolução e baixa definitiva',async()=>{
  const stamp=Date.now(),metadata=await request(app).get('/api/inventory/metadata').set('Authorization',`Bearer ${token}`),people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const product=await request(app).post('/api/inventory/products').set('Authorization',`Bearer ${token}`).send({sku:`WF-${stamp}`,name:'Material de fluxo QA',unit:'un',minimumStock:1})
  assert.equal(product.status,201)
  const entry=await request(app).post('/api/inventory/movements').set('Authorization',`Bearer ${token}`).send({kind:'entry',productId:product.body.data.id,locationId:metadata.body.locations[0].id,quantity:10,unitCost:5,occurredAt:'2091-01-01'})
  assert.equal(entry.status,201)
  const initial=await request(app).get('/api/inventory/workflows').set('Authorization',`Bearer ${token}`)
  const requisition=await request(app).post('/api/inventory/requisitions').set('Authorization',`Bearer ${token}`).send({departmentId:initial.body.departments[0].id,requesterId:people.body.data[0].id,requestedOn:'2091-01-02',neededOn:'2091-01-03',purpose:'Uso pastoral',items:[{productId:product.body.data.id,quantity:2}]})
  assert.equal(requisition.status,201)
  assert.equal((await request(app).post(`/api/inventory/requisitions/${requisition.body.data.id}/approve`).set('Authorization',`Bearer ${token}`).send({})).status,200)
  const afterApproval=await request(app).get('/api/inventory/workflows').set('Authorization',`Bearer ${token}`),requestItem=afterApproval.body.requisitionItems.find(item=>item.requisition_id===requisition.body.data.id)
  const fulfilled=await request(app).post(`/api/inventory/requisitions/${requisition.body.data.id}/fulfill`).set('Authorization',`Bearer ${token}`).send({locationId:metadata.body.locations[0].id,occurredAt:'2091-01-03',items:[{itemId:requestItem.id,quantity:2}]})
  assert.equal(fulfilled.body.data.status,'fulfilled')
  const order=await request(app).post('/api/inventory/purchase-orders').set('Authorization',`Bearer ${token}`).send({supplierName:'Fornecedor de materiais QA',orderedOn:'2091-01-04',expectedOn:'2091-01-10',items:[{productId:product.body.data.id,quantity:5,unitCost:6}]})
  assert.equal(order.status,201)
  const afterOrder=await request(app).get('/api/inventory/workflows').set('Authorization',`Bearer ${token}`),orderItem=afterOrder.body.purchaseOrderItems.find(item=>item.purchase_order_id===order.body.data.id)
  const received=await request(app).post(`/api/inventory/purchase-orders/${order.body.data.id}/receive`).set('Authorization',`Bearer ${token}`).send({locationId:metadata.body.locations[0].id,receivedOn:'2091-01-10',items:[{itemId:orderItem.id,quantity:5,batch:'L-QA'}]})
  assert.equal(received.body.data.status,'received')
  const returned=await request(app).post('/api/inventory/returns').set('Authorization',`Bearer ${token}`).send({requisitionId:requisition.body.data.id,productId:product.body.data.id,locationId:metadata.body.locations[0].id,personId:people.body.data[0].id,quantity:1,returnedOn:'2091-01-11',condition:'Bom'})
  assert.equal(returned.status,201)
  const writeoff=await request(app).post('/api/inventory/writeoffs').set('Authorization',`Bearer ${token}`).send({productId:product.body.data.id,locationId:metadata.body.locations[0].id,quantity:1,writtenOffOn:'2091-01-12',reason:'Material danificado',authorization:'ADM-QA'})
  assert.equal(writeoff.status,201)
  const overview=await request(app).get('/api/inventory/workflows').set('Authorization',`Bearer ${token}`)
  assert.ok(overview.body.returns.some(item=>item.id===returned.body.data.id))
  assert.ok(overview.body.writeoffs.some(item=>item.id===writeoff.body.data.id))
})

test('controla capacidade de sepultura e sepultamento',async()=>{
  const metadata=await request(app).get('/api/cemetery/metadata').set('Authorization',`Bearer ${token}`)
  const grave=await request(app).post('/api/cemetery/graves').set('Authorization',`Bearer ${token}`).send({sectorId:metadata.body.sectors[0].id,code:`QA-${Date.now()}`,type:'grave',capacity:1,status:'available'})
  assert.equal(grave.status,201)
  const deceased=await request(app).post('/api/cemetery/deceased').set('Authorization',`Bearer ${token}`).send({name:'Falecido de teste',deathDate:'2026-08-20',deathCertificate:`CERT-${Date.now()}`})
  assert.equal(deceased.status,201)
  const burial=await request(app).post('/api/cemetery/burials').set('Authorization',`Bearer ${token}`).send({graveId:grave.body.data.id,deceasedId:deceased.body.data.id,buriedAt:'2026-08-21'})
  assert.equal(burial.status,201)
  const graves=await request(app).get('/api/cemetery/graves').set('Authorization',`Bearer ${token}`)
  const updated=graves.body.data.find(item=>item.id===grave.body.data.id)
  assert.equal(updated.status,'full')
  assert.equal(updated.occupied,1)
})

test('campanha integra compromissos, recebimentos e despesas ao financeiro',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const campaign=await request(app).post('/api/campaigns').set('Authorization',`Bearer ${token}`).send({name:`Campanha QA ${Date.now()}`,campaignType:'construction',startsOn:'2026-09-01',endsOn:'2026-12-31',targetAmount:10000,status:'active'})
  assert.equal(campaign.status,201)
  const pledge=await request(app).post(`/api/campaigns/${campaign.body.data.id}/pledges`).set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,amount:500,frequency:'once',pledgedOn:'2026-09-01',dueDate:'2026-09-30'})
  assert.equal(pledge.status,201)
  const donation=await request(app).post(`/api/campaigns/${campaign.body.data.id}/donations`).set('Authorization',`Bearer ${token}`).send({pledgeId:pledge.body.data.id,amount:500,receivedOn:'2026-09-10',paymentMethod:'pix'})
  assert.equal(donation.status,201)
  assert.ok(donation.body.data.financial_transaction_id)
  const expense=await request(app).post(`/api/campaigns/${campaign.body.data.id}/expenses`).set('Authorization',`Bearer ${token}`).send({description:'Material de divulgação',amount:75,occurredOn:'2026-09-11'})
  assert.equal(expense.status,201)
  const campaigns=await request(app).get('/api/campaigns').set('Authorization',`Bearer ${token}`)
  const updated=campaigns.body.data.find(item=>item.id===campaign.body.data.id)
  assert.equal(Number(updated.received_amount),500)
  assert.equal(Number(updated.expense_amount),75)
  const details=await request(app).get(`/api/campaigns/${campaign.body.data.id}/details`).set('Authorization',`Bearer ${token}`)
  assert.equal(details.body.pledges[0].status,'fulfilled')
})

test('contabilidade exige partidas balanceadas e produz balancete',async()=>{
  const accounts=await request(app).get('/api/accounting/accounts').set('Authorization',`Bearer ${token}`)
  const cash=accounts.body.data.find(item=>item.code==='1.1.01'),revenue=accounts.body.data.find(item=>item.code==='4.1.01')
  const invalid=await request(app).post('/api/accounting/entries').set('Authorization',`Bearer ${token}`).send({entryDate:'2027-01-10',memo:'Lançamento inválido',status:'posted',lines:[{accountId:cash.id,debit:100,credit:0},{accountId:revenue.id,debit:0,credit:90}]})
  assert.equal(invalid.status,400)
  const entry=await request(app).post('/api/accounting/entries').set('Authorization',`Bearer ${token}`).send({entryDate:'2027-01-10',memo:'Receita contábil de teste',status:'posted',lines:[{accountId:cash.id,debit:100,credit:0},{accountId:revenue.id,debit:0,credit:100}]})
  assert.equal(entry.status,201)
  const trial=await request(app).get('/api/accounting/trial-balance?from=2027-01-01&to=2027-12-31').set('Authorization',`Bearer ${token}`)
  const totalDebit=trial.body.data.reduce((sum,item)=>sum+Number(item.debit),0),totalCredit=trial.body.data.reduce((sum,item)=>sum+Number(item.credit),0)
  assert.equal(totalDebit,totalCredit)
  assert.ok(totalDebit>=100)
})

test('contabilidade mantém exercício, responsáveis, abertura, notas e demonstrações',async()=>{
  const year=2199,from=`${year}-01-01`,to=`${year}-12-31`
  const accounts=await request(app).get('/api/accounting/accounts').set('Authorization',`Bearer ${token}`)
  const cash=accounts.body.data.find(item=>item.code==='1.1.01'),equity=accounts.body.data.find(item=>item.code==='3')
  let exercise=await request(app).post('/api/accounting/exercises').set('Authorization',`Bearer ${token}`).send({year,startsOn:from,endsOn:to})
  if(exercise.status===409){const current=await request(app).get('/api/accounting/settings').set('Authorization',`Bearer ${token}`),existing=current.body.exercises.find(item=>item.year===year);exercise={body:{data:existing},status:200}}
  assert.ok([200,201].includes(exercise.status))
  const professional=await request(app).post('/api/accounting/professionals').set('Authorization',`Bearer ${token}`).send({role:'accountant',name:'Contabilista QA',document:'12345678900',registrationNumber:'CRC-QA',registrationState:'PA'})
  assert.equal(professional.status,201)
  for(const balance of [{accountId:cash.id,debit:500,credit:0},{accountId:equity.id,debit:0,credit:500}]){
    const response=await request(app).post('/api/accounting/opening-balances').set('Authorization',`Bearer ${token}`).send({exerciseId:exercise.body.data.id,...balance})
    assert.equal(response.status,201)
  }
  const disclosure=await request(app).post('/api/accounting/disclosures').set('Authorization',`Bearer ${token}`).send({exerciseId:exercise.body.data.id,statementType:'balance_sheet',title:'Critérios contábeis',content:'Demonstrações elaboradas pelo regime de competência.'})
  assert.equal(disclosure.status,201)
  const balanceSheet=await request(app).get(`/api/accounting/statements/balance-sheet?from=${from}&to=${to}`).set('Authorization',`Bearer ${token}`)
  assert.equal(balanceSheet.status,200)
  assert.ok(Number(balanceSheet.body.summary.asset)>=500)
  assert.ok(Number(balanceSheet.body.summary.equity)>=500)
  for(const type of ['general-ledger','cash-book','income-statement','cash-flow','equity-changes']){
    const statement=await request(app).get(`/api/accounting/statements/${type}?from=${from}&to=${to}`).set('Authorization',`Bearer ${token}`)
    assert.equal(statement.status,200)
  }
  const settings=await request(app).get('/api/accounting/settings').set('Authorization',`Bearer ${token}`)
  assert.ok(settings.body.professionals.some(item=>item.name==='Contabilista QA'))
  assert.ok(settings.body.disclosures.some(item=>item.title==='Critérios contábeis'))
  assert.equal(settings.body.openingBalances.filter(item=>item.exercise_id===exercise.body.data.id).reduce((sum,item)=>sum+Number(item.debit),0),500)
  assert.equal(settings.body.openingBalances.filter(item=>item.exercise_id===exercise.body.data.id).reduce((sum,item)=>sum+Number(item.credit),0),500)
})

test('patrimônio calcula depreciação e registra manutenção',async()=>{
  const metadata=await request(app).get('/api/assets/metadata').set('Authorization',`Bearer ${token}`)
  const asset=await request(app).post('/api/assets').set('Authorization',`Bearer ${token}`).send({categoryId:metadata.body.categories.find(item=>item.code==='EQUIP').id,locationId:metadata.body.locations[0].id,assetTag:`PAT-${Date.now()}`,name:'Projetor de teste',assetType:'equipment',acquisitionDate:'2026-01-01',acquisitionValue:1200,residualValue:0,usefulLifeMonths:120,depreciationMethod:'straight_line'})
  assert.equal(asset.status,201)
  const event=await request(app).post(`/api/assets/${asset.body.data.id}/events`).set('Authorization',`Bearer ${token}`).send({eventType:'maintenance',eventDate:'2027-01-01',amount:50,description:'Revisão preventiva'})
  assert.equal(event.status,201)
  assert.equal(event.body.assetStatus,'maintenance')
  const assets=await request(app).get('/api/assets?asOf=2027-01-01').set('Authorization',`Bearer ${token}`)
  const updated=assets.body.data.find(item=>item.id===asset.body.data.id)
  assert.equal(Number(updated.accumulated_depreciation),120)
  assert.equal(Number(updated.book_value),1080)
})

test('gestão social vincula família, atendimento sigiloso e benefício',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const programs=await request(app).get('/api/social/programs').set('Authorization',`Bearer ${token}`)
  const household=await request(app).post('/api/social/households').set('Authorization',`Bearer ${token}`).send({referencePersonId:people.body.data[0].id,familyName:`Família QA ${Date.now()}`,monthlyIncome:900,vulnerabilityLevel:'high',status:'monitoring'})
  assert.equal(household.status,201)
  const assistance=await request(app).post('/api/social/assistance').set('Authorization',`Bearer ${token}`).send({householdId:household.body.data.id,attendedAt:'2026-08-20T15:00:00.000Z',assistanceType:'Visita domiciliar',summary:'Avaliação social automatizada',confidentiality:'strict',status:'follow_up'})
  assert.equal(assistance.status,201)
  const benefit=await request(app).post('/api/social/benefits').set('Authorization',`Bearer ${token}`).send({programId:programs.body.data[0].id,householdId:household.body.data.id,deliveredOn:'2026-08-20',benefit:'Cesta básica',quantity:1,estimatedValue:180,deliveredBy:'Equipe QA'})
  assert.equal(benefit.status,201)
  const details=await request(app).get(`/api/social/households/${household.body.data.id}/details`).set('Authorization',`Bearer ${token}`)
  assert.equal(details.body.members.length,1)
  assert.equal(details.body.records[0].confidentiality,'strict')
  assert.equal(Number(details.body.deliveries[0].estimated_value),180)
})

test('gestão social controla doações, estoque, kits, agenda e distribuições',async()=>{
  const stamp=Date.now(),people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`),households=await request(app).get('/api/social/households').set('Authorization',`Bearer ${token}`),center=await request(app).get('/api/social/distribution-center').set('Authorization',`Bearer ${token}`)
  const donor=await request(app).post('/api/social/donors').set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,name:`Doador QA ${stamp}`})
  assert.equal(donor.status,201)
  const product=await request(app).post('/api/social/products').set('Authorization',`Bearer ${token}`).send({productTypeId:center.body.productTypes[0].id,code:`SOC-${stamp}`,name:'Arroz social QA',unit:'kg',minimumStock:2})
  assert.equal(product.status,201)
  const entry=await request(app).post('/api/social/stock-movements').set('Authorization',`Bearer ${token}`).send({productId:product.body.data.id,kind:'entry',quantity:10,occurredOn:'2092-01-01',donorId:donor.body.data.id})
  assert.equal(entry.status,201)
  const kit=await request(app).post('/api/social/kits').set('Authorization',`Bearer ${token}`).send({code:`KIT-${stamp}`,name:'Cesta QA',items:[{productId:product.body.data.id,quantity:2}]})
  assert.equal(kit.status,201)
  const assembly=await request(app).post(`/api/social/kits/${kit.body.data.id}/assemble`).set('Authorization',`Bearer ${token}`).send({quantity:2,assembledOn:'2092-01-02'})
  assert.equal(assembly.status,201)
  const individual=await request(app).post('/api/social/distributions').set('Authorization',`Bearer ${token}`).send({distributionType:'individual',householdId:households.body.data[0].id,kitId:kit.body.data.id,quantity:1,distributedOn:'2092-01-03',deliveredBy:'Equipe QA'})
  assert.equal(individual.status,201)
  const community=await request(app).post('/api/social/distributions').set('Authorization',`Bearer ${token}`).send({distributionType:'community',communityName:'Comunidade QA',productId:product.body.data.id,quantity:2,distributedOn:'2092-01-04'})
  assert.equal(community.status,201)
  const schedule=await request(app).post('/api/social/schedules').set('Authorization',`Bearer ${token}`).send({title:'Mutirão social QA',scheduledFor:'2092-02-01T12:00:00.000Z',location:'Salão paroquial',audience:'Famílias'})
  assert.equal(schedule.status,201)
  const questionnaire=await request(app).post('/api/social/questionnaires').set('Authorization',`Bearer ${token}`).send({name:`Questionário QA ${stamp}`,questions:[{key:'renda',label:'Renda familiar',type:'number'}]})
  assert.equal(questionnaire.status,201)
  const overview=await request(app).get('/api/social/distribution-center').set('Authorization',`Bearer ${token}`)
  assert.equal(Number(overview.body.products.find(item=>item.id===product.body.data.id).stock),4)
  assert.equal(Number(overview.body.kits.find(item=>item.id===kit.body.data.id).available_quantity),1)
  assert.ok(overview.body.distributions.some(item=>item.id===individual.body.data.id))
})

test('catequese controla matrícula, encontro e frequência',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const metadata=await request(app).get('/api/catechesis/metadata').set('Authorization',`Bearer ${token}`)
  const group=await request(app).post('/api/catechesis/groups').set('Authorization',`Bearer ${token}`).send({name:`Turma QA ${Date.now()}`,stageId:metadata.body.stages[0].id,catechist:'Catequista QA',capacity:10,startsOn:'2026-08-01',endsOn:'2027-06-30'})
  assert.equal(group.status,201)
  const enrollment=await request(app).post(`/api/catechesis/groups/${group.body.data.id}/enrollments`).set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,enrolledAt:'2026-08-01'})
  assert.equal(enrollment.status,201)
  const session=await request(app).post(`/api/catechesis/groups/${group.body.data.id}/sessions`).set('Authorization',`Bearer ${token}`).send({sessionDate:'2026-08-22',startsAt:'09:00',endsAt:'10:30',topic:'Encontro de teste',sessionType:'class'})
  assert.equal(session.status,201)
  const attendance=await request(app).put(`/api/catechesis/sessions/${session.body.data.id}/attendance`).set('Authorization',`Bearer ${token}`).send({records:[{enrollmentId:enrollment.body.data.id,status:'present'}]})
  assert.equal(attendance.status,200)
  const details=await request(app).get(`/api/catechesis/groups/${group.body.data.id}/details`).set('Authorization',`Bearer ${token}`)
  assert.equal(Number(details.body.enrollments[0].attendance_percent),100)
  assert.equal(details.body.sessions[0].status,'held')
})

test('catequese emite certidão, registra livro e oblação e exporta ao sacramento',async()=>{
  const stamp=Date.now(),people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const metadata=await request(app).get('/api/catechesis/metadata').set('Authorization',`Bearer ${token}`)
  const stage=metadata.body.stages.find(item=>item.sacrament_type==='eucharist')
  const group=await request(app).post('/api/catechesis/groups').set('Authorization',`Bearer ${token}`).send({name:`Eucaristia documental ${stamp}`,stageId:stage.id,capacity:10})
  assert.equal(group.status,201)
  const enrollment=await request(app).post(`/api/catechesis/groups/${group.body.data.id}/enrollments`).set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,enrolledAt:'2094-01-01'})
  assert.equal(enrollment.status,201)
  const completed=await request(app).post(`/api/catechesis/enrollments/${enrollment.body.data.id}/complete`).set('Authorization',`Bearer ${token}`).send({completedAt:'2094-12-01'})
  assert.equal(completed.status,200)
  const certificateRequest=await request(app).post(`/api/catechesis/enrollments/${enrollment.body.data.id}/certificate-request`).set('Authorization',`Bearer ${token}`).send({requestedOn:'2094-12-02',purpose:'Arquivo familiar'})
  assert.equal(certificateRequest.status,201)
  const certificate=await request(app).post(`/api/catechesis/enrollments/${enrollment.body.data.id}/certificate`).set('Authorization',`Bearer ${token}`).send({requestId:certificateRequest.body.data.id})
  assert.equal(certificate.status,201)
  assert.ok(certificate.body.data.validation_code)
  const book=await request(app).post(`/api/catechesis/enrollments/${enrollment.body.data.id}/book-entry`).set('Authorization',`Bearer ${token}`).send({book:`CAT-${stamp}`,page:'12',entryNumber:'34',recordedOn:'2094-12-02'})
  assert.equal(book.status,201)
  const fee=await request(app).post(`/api/catechesis/enrollments/${enrollment.body.data.id}/fees`).set('Authorization',`Bearer ${token}`).send({description:'Material catequético',amount:35,dueOn:'2094-12-10'})
  assert.equal(fee.status,201)
  const paid=await request(app).post(`/api/catechesis/fees/${fee.body.data.id}/pay`).set('Authorization',`Bearer ${token}`).send({paidOn:'2094-12-03',paymentMethod:'Dinheiro'})
  assert.equal(paid.status,200)
  assert.ok(paid.body.receipt.startsWith('CAT-REC-'))
  const exported=await request(app).post(`/api/catechesis/enrollments/${enrollment.body.data.id}/export-sacrament`).set('Authorization',`Bearer ${token}`).send({requestedOn:'2094-12-04'})
  assert.equal(exported.status,201)
  assert.equal(exported.body.data.sacrament_type,'eucharist')
  const operations=await request(app).get(`/api/catechesis/operations?groupId=${group.body.data.id}`).set('Authorization',`Bearer ${token}`)
  assert.ok(operations.body.certificateRequests.some(item=>item.id===certificateRequest.body.data.id&&item.status==='issued'))
  assert.ok(operations.body.bookEntries.some(item=>item.id===book.body.data.id))
  assert.equal(operations.body.fees.find(item=>item.id===fee.body.data.id).status,'paid')
  const second=await request(app).post(`/api/catechesis/groups/${group.body.data.id}/enrollments`).set('Authorization',`Bearer ${token}`).send({personId:people.body.data[1].id,enrolledAt:'2094-01-01'})
  const cancelled=await request(app).post(`/api/catechesis/enrollments/${second.body.data.id}/cancel`).set('Authorization',`Bearer ${token}`).send({reason:'Mudança de paróquia'})
  assert.equal(cancelled.status,200)
  assert.equal(cancelled.body.data.status,'cancelled')
})

test('conectividade processa notificação e webhook assinado em fila',async()=>{
  const settings=await request(app).put('/api/settings/general').set('Authorization',`Bearer ${token}`).send({values:{timezone:'America/Belem',document:'QA'}})
  assert.equal(settings.status,200)
  const webhook=await request(app).post('/api/connectivity/webhooks').set('Authorization',`Bearer ${token}`).send({name:`Webhook QA ${Date.now()}`,endpointUrl:'internal://audit',eventTypes:['qa.completed']})
  assert.equal(webhook.status,201)
  assert.ok(webhook.body.signingSecret)
  const emitted=await request(app).post('/api/connectivity/events').set('Authorization',`Bearer ${token}`).send({eventType:'qa.completed',payload:{ok:true}})
  assert.equal(emitted.status,202)
  assert.ok(emitted.body.queued>=1)
  const notification=await request(app).post('/api/connectivity/notifications').set('Authorization',`Bearer ${token}`).send({channel:'internal',destination:'admin@nucleo.local',subject:'Teste',body:'Mensagem de teste'})
  assert.equal(notification.status,202)
  const processed=await request(app).post('/api/connectivity/process').set('Authorization',`Bearer ${token}`).send({})
  assert.equal(processed.status,200)
  assert.ok(processed.body.sent>=1)
  assert.ok(processed.body.webhooksDelivered>=1)
  const jobs=await request(app).get('/api/connectivity/notifications').set('Authorization',`Bearer ${token}`)
  assert.equal(jobs.body.data.find(item=>item.id===notification.body.data.id).status,'sent')
})

test('configurações administram usuário e registram auditoria',async()=>{
  const roles=await request(app).get('/api/settings/roles').set('Authorization',`Bearer ${token}`)
  const user=await request(app).post('/api/settings/users').set('Authorization',`Bearer ${token}`).send({name:'Usuário QA',email:`usuario.qa.${Date.now()}@local.test`,password:'senha-segura-123',roleIds:[roles.body.data[0].id]})
  assert.equal(user.status,201)
  const users=await request(app).get('/api/settings/users').set('Authorization',`Bearer ${token}`)
  assert.ok(users.body.data.some(item=>item.id===user.body.data.id))
  const auditLogs=await request(app).get('/api/settings/audit?limit=50').set('Authorization',`Bearer ${token}`)
  assert.ok(auditLogs.body.data.some(item=>item.entity==='users'&&item.entity_id===user.body.data.id))
})

test('ParóquiaNet publica conteúdo, ativa convite e valida credencial',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const person=people.body.data[0]
  const invite=await request(app).post('/api/portal/invitations').set('Authorization',`Bearer ${token}`).send({personId:person.id,email:person.email||`portal.${Date.now()}@local.test`})
  assert.equal(invite.status,201)
  assert.ok(invite.body.invitationToken)
  const accepted=await request(app).post(`/api/portal/invitations/${invite.body.invitationToken}/accept`).send({})
  assert.equal(accepted.status,200)
  assert.equal(accepted.body.membership.status,'active')
  const startsAt=new Date(Date.now()-60_000).toISOString()
  const announcement=await request(app).post('/api/portal/announcements').set('Authorization',`Bearer ${token}`).send({title:`Aviso portal QA ${Date.now()}`,body:'Conteúdo público de teste integrado',category:'Pastoral',audience:'all',startsAt,status:'published'})
  assert.equal(announcement.status,201)
  const schedule=await request(app).post('/api/portal/schedules').set('Authorization',`Bearer ${token}`).send({weekday:0,startsAt:'18:30',title:'Missa QA',community:'Matriz'})
  assert.equal(schedule.status,201)
  const credential=await request(app).post('/api/portal/credentials').set('Authorization',`Bearer ${token}`).send({personId:person.id,credentialType:'Encontro pastoral',validUntil:new Date(Date.now()+86_400_000).toISOString(),metadata:{source:'automated-test'}})
  assert.equal(credential.status,201)
  const validation=await request(app).get(`/api/portal/credentials/validate/${credential.body.data.code}`)
  assert.equal(validation.status,200)
  assert.equal(validation.body.valid,true)
  const used=await request(app).post(`/api/portal/credentials/${credential.body.data.id}/use`).set('Authorization',`Bearer ${token}`).send({})
  assert.equal(used.status,200)
  const publicPortal=await request(app).get(`/api/portal/public/${accepted.body.membership.organization_id}`)
  assert.equal(publicPortal.status,200)
  assert.ok(publicPortal.body.announcements.some(item=>item.id===announcement.body.data.id))
  assert.ok(publicPortal.body.schedules.some(item=>item.id===schedule.body.data.id))
})

test('Partilha Fraterna recebe, calcula, aprova e paga com integração financeira',async()=>{
  const existing=await request(app).get('/api/sharing/periods').set('Authorization',`Bearer ${token}`)
  const occupied=new Set(existing.body.data.map(item=>String(item.period_start).slice(0,10)))
  let offset=0,date
  do{date=new Date(Date.UTC(2050,0,1+offset++)).toISOString().slice(0,10)}while(occupied.has(date))
  const receipt=await request(app).post('/api/sharing/receipts').set('Authorization',`Bearer ${token}`).send({receiptType:'Doações',description:`Receita de partilha QA ${Date.now()}`,amount:1000,receivedOn:date,paymentMethod:'pix'})
  assert.equal(receipt.status,201)
  assert.ok(receipt.body.data.financial_transaction_id)
  const calculated=await request(app).post('/api/sharing/calculate').set('Authorization',`Bearer ${token}`).send({periodStart:date,periodEnd:date,excludedAmount:100,notes:'Teste automatizado'})
  assert.equal(calculated.status,201)
  assert.ok(Number(calculated.body.data.sharing_amount)>0)
  const approved=await request(app).post(`/api/sharing/periods/${calculated.body.data.id}/approve`).set('Authorization',`Bearer ${token}`).send({})
  assert.equal(approved.status,200)
  const payment=await request(app).post(`/api/sharing/periods/${calculated.body.data.id}/pay`).set('Authorization',`Bearer ${token}`).send({amount:Number(calculated.body.data.sharing_amount),paidOn:date,paymentMethod:'transfer',reference:'QA'})
  assert.equal(payment.status,201)
  assert.ok(payment.body.data.financial_transaction_id)
  const periods=await request(app).get('/api/sharing/periods').set('Authorization',`Bearer ${token}`)
  const period=periods.body.data.find(item=>item.id===calculated.body.data.id)
  assert.equal(period.status,'paid')
  assert.equal(Number(period.paid_amount),Number(period.sharing_amount))
})

test('fluxo sacramental controla exigências, padrinhos, oblação, livro e registro',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const application=await request(app).post('/api/sacramental/applications/baptism').set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,requestedOn:'2028-01-10',plannedDate:'2028-02-10',community:'Matriz'})
  assert.equal(application.status,201)
  let detail=await request(app).get(`/api/sacramental/applications/baptism/${application.body.data.id}`).set('Authorization',`Bearer ${token}`)
  assert.ok(detail.body.requirements.length>=2)
  for(const requirement of detail.body.requirements){
    const checked=await request(app).put(`/api/sacramental/application-requirements/${requirement.id}`).set('Authorization',`Bearer ${token}`).send({status:'received',receivedOn:'2028-01-11',reference:`DOC-${requirement.code}`})
    assert.equal(checked.status,200)
  }
  const witness=await request(app).post(`/api/sacramental/applications/${application.body.data.id}/witnesses`).set('Authorization',`Bearer ${token}`).send({name:'Padrinho QA',role:'godfather',canonicalEligibility:'eligible'})
  assert.equal(witness.status,201)
  const fee=await request(app).post(`/api/sacramental/applications/${application.body.data.id}/fees`).set('Authorization',`Bearer ${token}`).send({feeType:'oblation',description:'Oblação de batismo QA',amount:25,dueOn:'2028-02-10'})
  assert.equal(fee.status,201)
  const paid=await request(app).post(`/api/sacramental/fees/${fee.body.data.id}/pay`).set('Authorization',`Bearer ${token}`).send({paidOn:'2028-02-10',paymentMethod:'pix'})
  assert.equal(paid.status,200,JSON.stringify(paid.body))
  assert.ok(paid.body.financialTransactionId)
  const book=await request(app).post('/api/sacramental/books').set('Authorization',`Bearer ${token}`).send({sacramentType:'baptism',code:`BAT-QA-${Date.now()}`,title:'Livro automatizado de batismos',volume:1,startsOn:'2028-01-01',firstPage:1,lastPage:200})
  assert.equal(book.status,201)
  const registered=await request(app).post(`/api/sacramental/applications/${application.body.data.id}/register`).set('Authorization',`Bearer ${token}`).send({bookId:book.body.data.id,celebrationDate:'2028-02-10',celebrant:'Pe. Teste',page:'1',details:{godfather:'Padrinho QA'}})
  assert.equal(registered.status,201)
  assert.equal(registered.body.data.number,'1')
  detail=await request(app).get(`/api/sacramental/applications/baptism/${application.body.data.id}`).set('Authorization',`Bearer ${token}`)
  assert.equal(detail.body.application.status,'completed')
  assert.equal(detail.body.record.book_id,book.body.data.id)
})

test('processo matrimonial exige documentos, entrevista e proclamas antes da autorização',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  assert.ok(people.body.data.length>=2)
  const application=await request(app).post('/api/sacramental/applications/marriage').set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,relatedPersonId:people.body.data[1].id,requestedOn:'2029-03-01',plannedDate:'2029-06-15',community:'Matriz',civilEffect:true,processKind:'ordinary'})
  assert.equal(application.status,201)
  let detail=await request(app).get(`/api/sacramental/applications/marriage/${application.body.data.id}`).set('Authorization',`Bearer ${token}`)
  const premature=await request(app).post(`/api/marriage/cases/${detail.body.marriage.id}/authorize`).set('Authorization',`Bearer ${token}`).send({dispensations:[]})
  assert.equal(premature.status,409)
  for(const requirement of detail.body.requirements)await request(app).put(`/api/sacramental/application-requirements/${requirement.id}`).set('Authorization',`Bearer ${token}`).send({status:'received',receivedOn:'2029-03-02'})
  const interview=await request(app).post(`/api/marriage/cases/${detail.body.marriage.id}/interviews`).set('Authorization',`Bearer ${token}`).send({interviewee:'couple',scheduledAt:'2029-03-10T15:00:00.000Z',interviewer:'Pe. Teste',answers:{freeConsent:true},conclusion:'Aptos',status:'completed'})
  assert.equal(interview.status,201)
  const banns=await request(app).post(`/api/marriage/cases/${detail.body.marriage.id}/banns`).set('Authorization',`Bearer ${token}`).send({parish:'Paróquia Matriz',publicationStart:'2029-03-15',publicationEnd:'2029-03-30',result:'clear',certificateReference:'PROC-QA'})
  assert.equal(banns.status,201)
  const authorized=await request(app).post(`/api/marriage/cases/${detail.body.marriage.id}/authorize`).set('Authorization',`Bearer ${token}`).send({delegation:'Pároco local',consentNotes:'Consentimento livre',dispensations:[]})
  assert.equal(authorized.status,200)
  const book=await request(app).post('/api/sacramental/books').set('Authorization',`Bearer ${token}`).send({sacramentType:'marriage',code:`MAT-QA-${Date.now()}`,title:'Livro automatizado de matrimônios',volume:1,startsOn:'2029-01-01',firstPage:1,lastPage:200})
  const registered=await request(app).post(`/api/sacramental/applications/${application.body.data.id}/register`).set('Authorization',`Bearer ${token}`).send({bookId:book.body.data.id,celebrationDate:'2029-06-15',celebrant:'Pe. Teste',page:'1',details:{civilEffect:true}})
  assert.equal(registered.status,201)
  detail=await request(app).get(`/api/sacramental/applications/marriage/${application.body.data.id}`).set('Authorization',`Bearer ${token}`)
  assert.equal(detail.body.marriage.canonical_status,'celebrated')
})

test('cobrança PIX e recebível de cartão conciliam no financeiro',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const pix=await request(app).post('/api/payments/pix').set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,description:`PIX QA ${Date.now()}`,amount:81.25,expiresInMinutes:60})
  assert.equal(pix.status,201)
  assert.ok(pix.body.data.copy_paste_code)
  const settled=await request(app).post(`/api/payments/pix/${pix.body.data.id}/settle`).set('Authorization',`Bearer ${token}`).send({paidAt:'2031-04-10T12:00:00.000Z',endToEndId:`E2E-QA-${Date.now()}`})
  assert.equal(settled.status,200,JSON.stringify(settled.body))
  assert.ok(settled.body.financialTransactionId)
  const overview=await request(app).get('/api/payments/overview').set('Authorization',`Bearer ${token}`)
  assert.equal(overview.body.pix.find(item=>item.id===pix.body.data.id).status,'paid')
  const card=await request(app).post('/api/payments/cards').set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,brand:'Visa',authorizationCode:`AUTH-${Date.now()}`,saleDate:'2031-04-11',grossAmount:100,feeAmount:3.5,installmentCount:1,expectedOn:'2031-05-11'})
  assert.equal(card.status,201)
  assert.equal(Number(card.body.data.net_amount),96.5)
  const metadata=await request(app).get('/api/finance/metadata').set('Authorization',`Bearer ${token}`)
  const cardSettled=await request(app).post(`/api/payments/cards/${card.body.data.id}/settle`).set('Authorization',`Bearer ${token}`).send({settledOn:'2031-05-11',accountId:metadata.body.accounts[0].id})
  assert.equal(cardSettled.status,200)
})

test('boleto percorre emissão, remessa CNAB e retorno com baixa',async()=>{
  const metadata=await request(app).get('/api/finance/metadata').set('Authorization',`Bearer ${token}`)
  const agreement=await request(app).post('/api/payments/boleto-agreements').set('Authorization',`Bearer ${token}`).send({accountId:metadata.body.accounts[0].id,bankCode:'001',agreementNumber:`CONV-${Date.now()}`,wallet:'17',beneficiaryDocument:'12345678000199',beneficiaryName:'Paróquia QA',interestPercent:1,finePercent:2})
  assert.equal(agreement.status,201)
  const slip=await request(app).post('/api/payments/bank-slips').set('Authorization',`Bearer ${token}`).send({agreementId:agreement.body.data.id,payerName:'Pagador QA',payerDocument:'12345678901',description:'Contribuição via boleto',amount:145,dueDate:'2032-06-20'})
  assert.equal(slip.status,201)
  assert.equal(slip.body.data.barcode.length,44)
  const remittance=await request(app).post('/api/payments/remittances').set('Authorization',`Bearer ${token}`).send({agreementId:agreement.body.data.id,slipIds:[slip.body.data.id],layout:'CNAB240'})
  assert.equal(remittance.status,201)
  assert.match(remittance.body.data.content,/CNAB240/)
  const returned=await request(app).post('/api/payments/returns').set('Authorization',`Bearer ${token}`).send({agreementId:agreement.body.data.id,filename:`RET-${Date.now()}.txt`,layout:'CNAB240',occurrences:[{ourNumber:slip.body.data.our_number,status:'paid',occurrenceCode:'06',occurrenceDate:'2032-06-20',amount:145,bankReference:'BANCO-QA'}]})
  assert.equal(returned.status,201,JSON.stringify(returned.body))
  assert.equal(returned.body.paid,1)
  const overview=await request(app).get('/api/payments/overview').set('Authorization',`Bearer ${token}`)
  assert.equal(overview.body.slips.find(item=>item.id===slip.body.data.id).status,'paid')
})

test('documento fiscal gera conta, retenção e pacote EFD-Reinf rastreável',async()=>{
  const supplier=await request(app).post('/api/fiscal/suppliers').set('Authorization',`Bearer ${token}`).send({legalName:'Fornecedor Fiscal QA',document:`99${String(Date.now()).slice(-12)}`,email:'fiscal.qa@local.test',defaultCfop:'5102',taxRegime:'simples'})
  assert.equal(supplier.status,201)
  const document=await request(app).post('/api/fiscal/documents').set('Authorization',`Bearer ${token}`).send({supplierId:supplier.body.data.id,documentType:'nfse',number:`NF-${Date.now()}`,series:'A',issuedOn:'2033-01-15',competenceDate:'2033-01-01',description:'Serviço contábil QA',grossAmount:1000,discountAmount:0,taxAmount:45,netAmount:955,cfop:'5933'})
  assert.equal(document.status,201)
  assert.equal(document.body.data.status,'validated')
  const metadata=await request(app).get('/api/finance/metadata').set('Authorization',`Bearer ${token}`)
  const approved=await request(app).post(`/api/fiscal/documents/${document.body.data.id}/approve`).set('Authorization',`Bearer ${token}`).send({dueDate:'2033-02-10',categoryId:metadata.body.categories.find(item=>item.kind==='expense').id,costCenterId:metadata.body.costCenters[0].id})
  assert.equal(approved.status,200,JSON.stringify(approved.body))
  assert.ok(approved.body.payableId)
  const withholding=await request(app).post('/api/fiscal/withholdings').set('Authorization',`Bearer ${token}`).send({fiscalDocumentId:document.body.data.id,beneficiaryType:'pj',beneficiaryDocument:supplier.body.data.document,taxType:'IRRF',calculationBase:1000,rate:1.5,competence:'2033-01-01',dueDate:'2033-02-20'})
  assert.equal(withholding.status,201)
  assert.equal(Number(withholding.body.data.amount),15)
  const generated=await request(app).post('/api/compliance/generate').set('Authorization',`Bearer ${token}`).send({obligationType:'efd_reinf',periodStart:'2033-01-01',periodEnd:'2033-01-31'})
  assert.equal(generated.status,201)
  assert.equal(generated.body.data.status,'ready')
  const submitted=await request(app).post(`/api/compliance/${generated.body.data.id}/submit`).set('Authorization',`Bearer ${token}`).send({})
  assert.equal(submitted.status,200)
  assert.match(submitted.body.data.protocol,/^LOCAL-/)
})

test('cadastro paroquial integra família, pastoral, atendimento, LGPD e transferência',async()=>{
  const stamp=Date.now(),person=await request(app).post('/api/people').set('Authorization',`Bearer ${token}`).send({name:`Fiel Cadastro QA ${stamp}`,document:`QA-${stamp}`,birthDate:'1990-05-12',phone:'91999990000',address:'Rua de Teste',neighborhood:'Centro',city:'Belém',state:'PA'})
  assert.equal(person.status,201,JSON.stringify(person.body))
  const related=await request(app).post('/api/people').set('Authorization',`Bearer ${token}`).send({name:`Familiar Cadastro QA ${stamp}`})
  const community=await request(app).post('/api/people-center/communities').set('Authorization',`Bearer ${token}`).send({name:`Comunidade QA ${stamp}`,patron:'São Teste',coordinatorPersonId:person.body.data.id})
  assert.equal(community.status,201)
  const household=await request(app).post('/api/people-center/households').set('Authorization',`Bearer ${token}`).send({name:`Família QA ${stamp}`,communityId:community.body.data.id,address:'Rua da Família',members:[{personId:person.body.data.id,relationship:'Responsável',isResponsible:true}]})
  assert.equal(household.status,201,JSON.stringify(household.body))
  const entity=await request(app).post('/api/people-center/pastoral-entities').set('Authorization',`Bearer ${token}`).send({name:`Pastoral QA ${stamp}`,entityType:'pastoral',communityId:community.body.data.id,meetingSchedule:'Sábados às 18h'})
  assert.equal(entity.status,201)
  const relationship=await request(app).post('/api/people-center/relationships').set('Authorization',`Bearer ${token}`).send({personId:person.body.data.id,relatedPersonId:related.body.data.id,relationshipType:'Responsável',reciprocalType:'Dependente'})
  assert.equal(relationship.status,201)
  const volunteer=await request(app).post('/api/people-center/volunteer-terms').set('Authorization',`Bearer ${token}`).send({personId:person.body.data.id,entityId:entity.body.data.id,termVersion:`QA-${stamp}`,activity:'Acolhida',startedOn:'2034-01-01',accepted:true})
  assert.equal(volunteer.status,201)
  const membership=await request(app).post('/api/people-center/pastoral-memberships').set('Authorization',`Bearer ${token}`).send({entityId:entity.body.data.id,personId:person.body.data.id,roleName:'Coordenador',isCoordinator:true,joinedOn:'2034-01-10'})
  assert.equal(membership.status,201)
  const attendance=await request(app).post('/api/people-center/attendances').set('Authorization',`Bearer ${token}`).send({personId:person.body.data.id,communityId:community.body.data.id,channel:'presential',serviceType:'Secretaria',subject:'Atualização cadastral',description:'Atendimento automatizado'})
  assert.equal(attendance.status,201)
  assert.match(attendance.body.data.protocol,/^ATD-/)
  const resolved=await request(app).post(`/api/people-center/attendances/${attendance.body.data.id}/resolve`).set('Authorization',`Bearer ${token}`).send({resolution:'Cadastro atualizado e conferido'})
  assert.equal(resolved.status,200)
  const consent=await request(app).post('/api/people-center/consents').set('Authorization',`Bearer ${token}`).send({personId:person.body.data.id,purpose:'Comunicação pastoral',legalBasis:'Consentimento',channel:'written',termVersion:`QA-${stamp}`,evidence:'Termo físico QA'})
  assert.equal(consent.status,201)
  const lgpd=await request(app).post('/api/people-center/lgpd-requests').set('Authorization',`Bearer ${token}`).send({personId:person.body.data.id,requestType:'access',description:'Cópia dos dados',dueAt:'2034-02-10'})
  assert.equal(lgpd.status,201)
  const lgpdDone=await request(app).post(`/api/people-center/lgpd-requests/${lgpd.body.data.id}/resolve`).set('Authorization',`Bearer ${token}`).send({status:'completed',response:'Relatório entregue ao titular'})
  assert.equal(lgpdDone.status,200)
  const transfer=await request(app).post('/api/people-center/transfers').set('Authorization',`Bearer ${token}`).send({personId:person.body.data.id,direction:'outgoing',originDestination:'Paróquia Destino QA',requestedOn:'2034-01-20',reason:'Mudança de domicílio'})
  assert.equal(transfer.status,201)
  const approved=await request(app).post(`/api/people-center/transfers/${transfer.body.data.id}/status`).set('Authorization',`Bearer ${token}`).send({status:'approved',effectiveOn:'2034-01-25'})
  assert.equal(approved.status,200)
  const field=await request(app).post('/api/people-center/field-definitions').set('Authorization',`Bearer ${token}`).send({label:`Carisma QA ${stamp}`,fieldKey:`carisma_qa_${stamp}`,fieldType:'text',options:[],required:false})
  assert.equal(field.status,201)
  const value=await request(app).put(`/api/people/${person.body.data.id}/field-values`).set('Authorization',`Bearer ${token}`).send({values:[{fieldDefinitionId:field.body.data.id,value:'Acolhida'}]})
  assert.equal(value.status,200)
  const overview=await request(app).get('/api/people-center/overview').set('Authorization',`Bearer ${token}`)
  assert.equal(overview.status,200)
  assert.equal(overview.body.households.find(x=>x.id===household.body.data.id).member_count,1)
  assert.equal(overview.body.entities.find(x=>x.id===entity.body.data.id).coordinator_count,1)
  assert.ok(overview.body.relationships.some(x=>x.id===relationship.body.data.id))
  assert.ok(overview.body.volunteerTerms.some(x=>x.id===volunteer.body.data.id&&x.status==='accepted'))
  assert.equal(overview.body.lgpdRequests.find(x=>x.id===lgpd.body.data.id).status,'completed')
})

test('dízimos e ofertas controlam competências, expectativa, documentos e PIX',async()=>{
  const stamp=Date.now(),person=await request(app).post('/api/people').set('Authorization',`Bearer ${token}`).send({name:`Dizimista QA ${stamp}`,phone:'91988887777'})
  assert.equal(person.status,201)
  const member=await request(app).post('/api/contributions/members').set('Authorization',`Bearer ${token}`).send({personId:person.body.data.id,joinedOn:'2026-01-01',monthlyExpectation:75,preferredPaymentDay:10,deliveryMethod:'pix'})
  assert.equal(member.status,201,JSON.stringify(member.body))
  assert.match(member.body.data.member_number,/^\d{6}$/)
  const payment=await request(app).post('/api/contributions/tithe-payments').set('Authorization',`Bearer ${token}`).send({memberId:member.body.data.id,amount:150,paymentDate:'2026-02-10',paymentMethod:'pix',reference:`QA-${stamp}`,competences:['2026-01-01','2026-02-01']})
  assert.equal(payment.status,201,JSON.stringify(payment.body))
  assert.match(payment.body.receipt,/^DIZ-/)
  const type=await request(app).post('/api/contributions/offering-types').set('Authorization',`Bearer ${token}`).send({name:`Oferta QA ${stamp}`,code:`O${stamp}`,description:'Oferta automatizada',defaultAmount:25,financialCategory:'offerings'})
  assert.equal(type.status,201)
  const offering=await request(app).post('/api/contributions/offerings').set('Authorization',`Bearer ${token}`).send({offeringTypeId:type.body.data.id,personId:person.body.data.id,amount:40,offeredOn:'2026-02-15',paymentMethod:'cash',reference:`OF-${stamp}`})
  assert.equal(offering.status,201)
  assert.ok(offering.body.data.financial_transaction_id)
  const pix=await request(app).post('/api/contributions/pix').set('Authorization',`Bearer ${token}`).send({kind:'tithe',memberId:member.body.data.id,amount:75,description:'Dízimo de março',expiresInMinutes:120})
  assert.equal(pix.status,201)
  assert.equal(pix.body.data.contribution_type,'tithe')
  const docs=await request(app).post('/api/contributions/documents').set('Authorization',`Bearer ${token}`).send({documentType:'carnet',memberIds:[member.body.data.id],periodStart:'2026-01-01',periodEnd:'2026-12-31'})
  assert.equal(docs.status,201)
  assert.equal(docs.body.data[0].payload.months.length,12)
  const overview=await request(app).get('/api/contributions/overview?year=2026').set('Authorization',`Bearer ${token}`)
  assert.equal(overview.status,200,JSON.stringify(overview.body))
  assert.equal(Number(overview.body.annual.find(x=>x.member_id===member.body.data.id).annual_total),150)
  assert.equal(Number(overview.body.monthly.find(x=>x.month===2).offerings)>=40,true)
  assert.equal(overview.body.documents.some(x=>x.tithe_member_id===member.body.data.id&&x.document_type==='carnet'),true)
})

test('patrimônio controla reserva, documentos, seguro, condutor e locação financeira',async()=>{
  const stamp=Date.now(),metadata=await request(app).get('/api/assets/metadata').set('Authorization',`Bearer ${token}`),people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`)
  const property=await request(app).post('/api/assets').set('Authorization',`Bearer ${token}`).send({assetTag:`IMO-${stamp}`,name:`Salão paroquial QA ${stamp}`,assetType:'property',categoryId:metadata.body.categories.find(x=>x.code==='IMOVEIS')?.id,locationId:metadata.body.locations[0].id,acquisitionDate:'2020-01-01',acquisitionValue:200000,residualValue:50000,usefulLifeMonths:300,depreciationMethod:'straight_line'})
  assert.equal(property.status,201)
  const reservation=await request(app).post('/api/assets/reservations').set('Authorization',`Bearer ${token}`).send({assetId:property.body.data.id,requesterId:people.body.data[0].id,title:'Retiro QA',startsAt:'2035-03-01T12:00:00.000Z',endsAt:'2035-03-02T12:00:00.000Z',purpose:'Retiro pastoral'})
  assert.equal(reservation.status,201)
  const conflict=await request(app).post('/api/assets/reservations').set('Authorization',`Bearer ${token}`).send({assetId:property.body.data.id,title:'Conflito QA',startsAt:'2035-03-01T18:00:00.000Z',endsAt:'2035-03-02T10:00:00.000Z'})
  assert.equal(conflict.status,409)
  const approved=await request(app).post(`/api/assets/reservations/${reservation.body.data.id}/status`).set('Authorization',`Bearer ${token}`).send({status:'approved'})
  assert.equal(approved.status,200)
  const legal=await request(app).post(`/api/assets/${property.body.data.id}/legal-documents`).set('Authorization',`Bearer ${token}`).send({documentType:'Matrícula',documentNumber:`MAT-${stamp}`,registryOffice:'1º Ofício',issuedOn:'2020-01-01'})
  assert.equal(legal.status,201)
  const insurance=await request(app).post(`/api/assets/${property.body.data.id}/insurance`).set('Authorization',`Bearer ${token}`).send({insurer:'Seguradora QA',policyNumber:`AP-${stamp}`,coverage:'Incêndio',insuredAmount:200000,premiumAmount:1200,startsOn:'2035-01-01',endsOn:'2035-12-31'})
  assert.equal(insurance.status,201)
  const lease=await request(app).post('/api/assets/leases').set('Authorization',`Bearer ${token}`).send({assetId:property.body.data.id,tenantPersonId:people.body.data[0].id,tenantName:people.body.data[0].name,startsOn:'2036-01-01',endsOn:'2036-03-31',monthlyAmount:900,dueDay:10,adjustmentIndex:'IPCA',depositAmount:900})
  assert.equal(lease.status,201,JSON.stringify(lease.body))
  assert.equal(lease.body.installments.length,3)
  assert.ok(lease.body.installments.every(x=>x.obligation_id))
  const vehicle=await request(app).post('/api/assets').set('Authorization',`Bearer ${token}`).send({assetTag:`VEI-${stamp}`,name:`Veículo QA ${stamp}`,assetType:'vehicle',plate:`QA${String(stamp).slice(-4)}`,acquisitionValue:50000,residualValue:10000,usefulLifeMonths:60,depreciationMethod:'straight_line'})
  assert.equal(vehicle.status,201)
  const driver=await request(app).post(`/api/assets/${vehicle.body.data.id}/drivers`).set('Authorization',`Bearer ${token}`).send({personId:people.body.data[0].id,licenseNumber:`CNH-${stamp}`,licenseCategory:'B',licenseExpiresOn:'2037-01-01',assignedOn:'2035-01-01'})
  assert.equal(driver.status,201)
  const accessory=await request(app).post(`/api/assets/${vehicle.body.data.id}/accessories`).set('Authorization',`Bearer ${token}`).send({name:'Estepe',quantity:1,condition:'Bom'})
  assert.equal(accessory.status,201)
  const operations=await request(app).get('/api/assets/operations').set('Authorization',`Bearer ${token}`)
  assert.equal(operations.status,200)
  assert.equal(operations.body.leases.find(x=>x.id===lease.body.data.id).installment_count,3)
  assert.equal(operations.body.drivers.some(x=>x.id===driver.body.data.id),true)
})

test('anexos preservam hash e relatórios geram CSV e PDF auditados',async()=>{
  const people=await request(app).get('/api/people').set('Authorization',`Bearer ${token}`),content=Buffer.from('Documento de teste dos anexos').toString('base64')
  const uploaded=await request(app).post('/api/attachments').set('Authorization',`Bearer ${token}`).send({entityType:'people',entityId:people.body.data[0].id,filename:'comprovante-qa.txt',mimeType:'text/plain',contentBase64:content,description:'Anexo automatizado'})
  assert.equal(uploaded.status,201,JSON.stringify(uploaded.body))
  assert.equal(Number(uploaded.body.data.size_bytes),29)
  const listed=await request(app).get('/api/attachments').query({entityType:'people',entityId:people.body.data[0].id}).set('Authorization',`Bearer ${token}`)
  assert.equal(listed.status,200)
  assert.equal(listed.body.data.some(x=>x.id===uploaded.body.data.id),true)
  const downloaded=await request(app).get(`/api/attachments/${uploaded.body.data.id}/download`).set('Authorization',`Bearer ${token}`)
  assert.equal(downloaded.status,200)
  assert.equal(downloaded.text,'Documento de teste dos anexos')
  const csv=await request(app).post('/api/reports/generate').set('Authorization',`Bearer ${token}`).send({reportType:'people',title:'Elenco de fiéis QA',format:'csv',status:'active'})
  assert.equal(csv.status,200)
  assert.match(csv.headers['content-type'],/text\/csv/)
  assert.match(csv.text,/Nome;|"Nome"/)
  const operational=await request(app).post('/api/registry/fieis-cadastros/relatorios-de-fieis').set('Authorization',`Bearer ${token}`).send({title:'Registro para relatório operacional',personId:people.body.data[0].id,status:'active',occurredAt:'2095-01-01',amount:10,data:{comunidade:'Centro'}})
  assert.equal(operational.status,201)
  const operationalReport=await request(app).post('/api/reports/generate').set('Authorization',`Bearer ${token}`).send({reportType:'operational',title:'Relatório operacional QA',format:'csv',moduleSlug:'fieis-cadastros',resourceSlug:'relatorios-de-fieis'})
  assert.equal(operationalReport.status,200,operationalReport.text)
  assert.match(operationalReport.text,/Registro para relatório operacional/)
  const pdf=await request(app).post('/api/reports/generate').set('Authorization',`Bearer ${token}`).send({reportType:'assets',title:'Inventário patrimonial QA',format:'pdf',status:'active'})
  assert.equal(pdf.status,200,Buffer.from(pdf.body).toString())
  assert.equal(Buffer.from(pdf.body).subarray(0,4).toString(),'%PDF')
  const history=await request(app).get('/api/reports/history').set('Authorization',`Bearer ${token}`)
  assert.equal(history.status,200)
  assert.equal(history.body.data.some(x=>x.id===pdf.headers['x-report-id']&&x.row_count>0),true)
})

after(async()=>{await pool.end()})
