CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, type text NOT NULL DEFAULT 'parish', parent_id uuid REFERENCES organizations(id), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, email text NOT NULL UNIQUE, password_hash text NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS user_roles (user_id uuid REFERENCES users(id) ON DELETE CASCADE, role_id uuid REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY(user_id, role_id));
CREATE TABLE IF NOT EXISTS role_permissions (role_id uuid REFERENCES roles(id) ON DELETE CASCADE, permission_id uuid REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id, permission_id));
CREATE TABLE IF NOT EXISTS people (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, document text, birth_date date, phone text, email text, status text NOT NULL DEFAULT 'active', notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS people_org_name_idx ON people(organization_id, lower(name));
CREATE TABLE IF NOT EXISTS financial_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, type text NOT NULL DEFAULT 'cash', opening_balance numeric(14,2) NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS financial_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), account_id uuid REFERENCES financial_accounts(id), person_id uuid REFERENCES people(id), kind text NOT NULL CHECK (kind IN ('income','expense','transfer')), category text NOT NULL, description text NOT NULL, amount numeric(14,2) NOT NULL CHECK (amount > 0), occurred_at date NOT NULL DEFAULT current_date, source text, external_id text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS financial_org_date_idx ON financial_transactions(organization_id, occurred_at DESC);
CREATE TABLE IF NOT EXISTS tithe_payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), person_id uuid REFERENCES people(id), amount numeric(14,2) NOT NULL CHECK (amount > 0), payment_date date NOT NULL DEFAULT current_date, payment_method text NOT NULL DEFAULT 'pix', reference text, financial_transaction_id uuid REFERENCES financial_transactions(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid REFERENCES users(id), action text NOT NULL, entity text NOT NULL, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());

INSERT INTO organizations (id, name, type) VALUES ('00000000-0000-0000-0000-000000000001', 'Paróquia Santa Luzia', 'parish') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('Administrador') ON CONFLICT DO NOTHING;
INSERT INTO permissions (code) VALUES ('people.view'),('people.create'),('people.update'),('finance.view'),('finance.create'),('tithe.view'),('tithe.create'),('audit.view') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.name='Administrador' ON CONFLICT DO NOTHING;
INSERT INTO financial_accounts (organization_id, name, type) SELECT '00000000-0000-0000-0000-000000000001', 'Caixa principal', 'cash' WHERE NOT EXISTS (SELECT 1 FROM financial_accounts WHERE name='Caixa principal');
INSERT INTO people (organization_id, name, document, phone, email) SELECT '00000000-0000-0000-0000-000000000001', x.name, x.document, x.phone, x.email FROM (VALUES ('Maria Aparecida Silva','123.456.789-00','(91) 98888-1001','maria@exemplo.local'),('Raimundo Nonato Costa','987.654.321-00','(91) 98888-1002','raimundo@exemplo.local'),('João Pedro Santos','456.789.123-00','(91) 98888-1003','joao@exemplo.local')) x(name,document,phone,email) WHERE NOT EXISTS (SELECT 1 FROM people);
