import { useEffect, useState } from 'react'
import { api } from './api'
import { AttachmentCenter, ReportCenter } from './ReportAttachmentCenter'

function IssueDialog({ templates, people, onClose, onIssued }) {
  const [error,setError]=useState('')
  const issue=async event=>{event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget));try{await api('/documents/issue',{method:'POST',body:JSON.stringify({templateCode:raw.templateCode,personId:raw.personId,values:{book:raw.book,page:raw.page,number:raw.number,celebration_date:raw.celebrationDate,description:raw.description,amount:raw.amount,occurred_at:raw.occurredAt}})});onIssued()}catch(err){setError(err.message)}}
  return <div className="modal-backdrop"><div className="modal-card"><div className="modal-heading"><div><span className="eyebrow">CENTRAL DE DOCUMENTOS</span><h2>Emitir documento</h2></div><button className="close-btn" onClick={onClose}>×</button></div><form className="record-form" onSubmit={issue}><label>Modelo<select name="templateCode" required><option value="">Selecione</option>{templates.map(item=><option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label>Pessoa<select name="personId"><option value="">Sem vínculo</option>{people.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label><div className="form-grid"><label>Livro<input name="book" /></label><label>Folha<input name="page" /></label></div><div className="form-grid"><label>Número<input name="number" /></label><label>Data da celebração<input name="celebrationDate" type="date" /></label></div><label>Descrição<input name="description" /></label><div className="form-grid"><label>Valor<input name="amount" /></label><label>Data do recebimento<input name="occurredAt" type="date" /></label></div>{error?<div className="form-error">{error}</div>:null}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">Emitir documento</button></div></form></div></div>
}

export default function DocumentCenter(){
  const [templates,setTemplates]=useState([]),[emissions,setEmissions]=useState([]),[people,setPeople]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('documents')
  const load=async()=>{try{const [t,e,p]=await Promise.all([api('/documents/templates'),api('/documents/emissions'),api('/people')]);setTemplates(t.data);setEmissions(e.data);setPeople(p.data)}catch(err){setError(err.message)}}
  useEffect(()=>{load()},[])
  const download=async emission=>{const response=await fetch(`/api/documents/emissions/${emission.id}/pdf`,{headers:{Authorization:`Bearer ${localStorage.getItem('nucleo_token')}`}});if(!response.ok)return setError('Falha ao gerar o PDF');const url=URL.createObjectURL(await response.blob());window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}
  return <><section className="module-header document-header"><div><span className="eyebrow">DOCUMENTOS E INFORMAÇÃO</span><h1>Central de documentos</h1><p>Certidões, relatórios, impressão, anexos e validação de autenticidade.</p></div>{tab==='documents'&&<button className="primary" onClick={()=>setOpen(true)}>＋ Emitir documento</button>}</section><div className="finance-tabs"><button className={tab==='documents'?'active':''} onClick={()=>setTab('documents')}>Documentos oficiais</button><button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}>Relatórios e exportações</button><button className={tab==='attachments'?'active':''} onClick={()=>setTab('attachments')}>Anexos</button></div>{error?<div className="form-error">{error}</div>:null}{tab==='documents'&&<div className="document-grid"><div className="panel document-templates"><div className="panel-heading"><div><span className="eyebrow">MODELOS</span><h3>Modelos disponíveis</h3></div></div>{templates.map(item=><button key={item.id} onClick={()=>setOpen(true)}><span className="document-icon">▤</span><span><strong>{item.name}</strong><small>{item.document_type}</small></span><i>›</i></button>)}</div><div className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">HISTÓRICO</span><h3>Documentos emitidos</h3></div></div><table><thead><tr><th>Documento</th><th>Pessoa</th><th>Emissão</th><th>Validação</th><th></th></tr></thead><tbody>{emissions.map(item=><tr key={item.id}><td><strong>{item.title}</strong><small className="record-details">{item.template_name}</small></td><td>{item.person_name||'—'}</td><td>{new Date(item.emitted_at).toLocaleString('pt-BR')}</td><td><code>{item.validation_code}</code></td><td><button className="text-btn" onClick={()=>download(item)}>Abrir PDF ↗</button></td></tr>)}</tbody></table>{!emissions.length?<div className="registry-empty"><strong>Nenhum documento emitido</strong><p>Escolha um modelo para gerar a primeira via.</p></div>:null}</div></div>}{tab==='reports'&&<ReportCenter/>}{tab==='attachments'&&<AttachmentCenter/>}{open?<IssueDialog templates={templates} people={people} onClose={()=>setOpen(false)} onIssued={async()=>{setOpen(false);await load()}}/>:null}</>
}
