import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const modules = [
  ['Visão geral', '⌂'], ['Fiéis e Cadastros', '◉'], ['Dízimos e Ofertas', '◌'], ['Financeiro', '₿'],
  ['Batismo', '✦'], ['Catequese', '✧'], ['Crisma', '✦'], ['Eucaristia', '◈'], ['Matrimônio', '∞'],
  ['Campanhas', '◎'], ['Agendas e Cursos', '◷'], ['Almoxarifado', '▦'], ['Cemitério', '▥'],
  ['Contábil', '∑'], ['Patrimônio', '◆'], ['Gestão Social', '♧'], ['Conectividade', '⌁'],
]
const sectionData = {
  'Batismo': { title: 'Registros de batismo', subtitle: 'Inscrições, celebrações e livros sacramentais', tabs: ['Inscrições', 'Registros', 'Livro', 'Certidões'], accent: 'blue', fields: ['Data da celebração', 'Celebrante', 'Livro e folha'] },
  'Catequese': { title: 'Acompanhamento catequético', subtitle: 'Turmas, etapas, presença e certificados', tabs: ['Catequizandos', 'Turmas', 'Presença', 'Certificados'], accent: 'gold', fields: ['Etapa', 'Turma', 'Catequista'] },
  'Crisma': { title: 'Registros de crisma', subtitle: 'Preparação, celebração e emissão de certificados', tabs: ['Inscrições', 'Registros', 'Livro', 'Certidões'], accent: 'green', fields: ['Padrinho/madrinha', 'Ministro', 'Livro e número'] },
  'Eucaristia': { title: 'Primeira Eucaristia', subtitle: 'Catequizandos, celebrações e certificados', tabs: ['Inscrições', 'Celebrações', 'Livro', 'Certificados'], accent: 'gold', fields: ['Grupo catequético', 'Data', 'Celebrante'] },
  'Matrimônio': { title: 'Processos matrimoniais', subtitle: 'Habilitação, proclamas, entrevistas e celebração', tabs: ['Processos', 'Documentos', 'Proclamas', 'Celebrações'], accent: 'terra', fields: ['Noivo e noiva', 'Data prevista', 'Situação canônica'] },
  'Campanhas': { title: 'Campanhas e arrecadações', subtitle: 'Metas, doadores, recebimentos e projeções', tabs: ['Campanhas', 'Recebimentos', 'Doadores', 'Relatórios'], accent: 'green', fields: ['Meta', 'Período', 'Responsável'] },
  'Agendas e Cursos': { title: 'Agenda paroquial', subtitle: 'Compromissos, cursos, encontros e inscrições', tabs: ['Agenda', 'Cursos', 'Participantes', 'Certificados'], accent: 'blue', fields: ['Início e término', 'Local', 'Responsável'] },
  'Almoxarifado': { title: 'Almoxarifado', subtitle: 'Produtos, entradas, saídas e estoque mínimo', tabs: ['Produtos', 'Movimentações', 'Inventário', 'Relatórios'], accent: 'green', fields: ['Produto', 'Quantidade', 'Estoque mínimo'] },
  'Cemitério': { title: 'Gestão do cemitério', subtitle: 'Quadras, sepulturas, falecidos e concessões', tabs: ['Sepulturas', 'Falecidos', 'Concessões', 'Relatórios'], accent: 'terra', fields: ['Falecido', 'Quadra e jazigo', 'Responsável'] },
  'Contábil': { title: 'Contabilidade paroquial', subtitle: 'Plano de contas, centros de custo e fechamentos', tabs: ['Plano de contas', 'Centros de custo', 'Fechamentos', 'Relatórios'], accent: 'blue', fields: ['Código', 'Descrição', 'Centro de custo'] },
  'Patrimônio': { title: 'Patrimônio', subtitle: 'Bens, imóveis, veículos, inventário e depreciação', tabs: ['Bens móveis', 'Imóveis', 'Veículos', 'Inventário'], accent: 'gold', fields: ['Bem', 'Localização', 'Responsável'] },
  'Gestão Social': { title: 'Gestão social', subtitle: 'Atendimentos, famílias, benefícios e encaminhamentos', tabs: ['Atendimentos', 'Famílias', 'Benefícios', 'Relatórios'], accent: 'terra', fields: ['Atendido', 'Tipo de atendimento', 'Encaminhamento'] },
  'Conectividade': { title: 'Conectividade', subtitle: 'Integrações, notificações, webhooks e serviços', tabs: ['Integrações', 'Notificações', 'Webhooks', 'Logs'], accent: 'green', fields: ['Serviço', 'Evento', 'Situação'] },
}
const navGroups = { 'Fiéis e Cadastros': ['Cadastro de fiéis', 'Relatórios de fiéis', 'Registro de atendimento', 'Campos do perfil'], 'Dízimos e Ofertas': ['Lançamento de dízimo', 'Extrato de dízimo', 'Dízimos no período', 'Comparativo do dízimo', 'Lançamento de oferta'], Financeiro: ['Movimentação de caixa', 'Movimentação bancária', 'Conciliação', 'Prestação de contas', 'Relatórios financeiros'] }
const api = async (path, options = {}) => { const token = localStorage.getItem('nucleo_token'); const response = await fetch(`/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Falha na comunicação'); return data }
const money = value => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span> }

function Login({ onLogin }) { const [email, setEmail] = useState('admin@nucleo.local'); const [password, setPassword] = useState('admin123'); const [error, setError] = useState(''); const submit = async event => { event.preventDefault(); try { const data = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('nucleo_token', data.token); onLogin(data.user) } catch (err) { setError(err.message) } }; return <div className="login-page"><div className="login-card"><div className="brand login-brand"><div className="brand-mark">N</div><div><strong>Núcleo</strong><span>Eclesial</span></div></div><span className="eyebrow">AMBIENTE LOCAL</span><h1>Entre no seu espaço pastoral</h1><p>Gestão integrada para paróquias, comunidades e dioceses.</p><form onSubmit={submit}><label>E-mail<input value={email} onChange={event => setEmail(event.target.value)} type="email" required /></label><label>Senha<input value={password} onChange={event => setPassword(event.target.value)} type="password" required /></label>{error && <div className="form-error">{error}</div>}<button className="primary login-submit">Entrar</button></form><small>Demo local: admin@nucleo.local · admin123</small></div></div> }
function Sidebar({ active, onSelect, onLogout }) { return <aside className="sidebar"><div className="brand"><div className="brand-mark">N</div><div><strong>Núcleo</strong><span>Eclesial</span></div></div><div className="side-caption">ÁREA DE TRABALHO</div><nav className="module-nav">{modules.map(([label, glyph]) => <button key={label} className={active === label ? 'active' : ''} onClick={() => onSelect(label)}><Icon>{glyph}</Icon><span>{label}</span>{active === label && <i />}</button>)}</nav><div className="sidebar-bottom"><button onClick={() => onSelect('Configurações')}><Icon>⚙</Icon><span>Configurações</span></button><button onClick={onLogout}><Icon>↪</Icon><span>Sair</span></button><div className="sidebar-version">Núcleo Eclesial <b>v0.3</b></div></div></aside> }
function Topbar({ user, onSearch }) { return <header className="topbar"><div className="crumb"><span>Diocese de Bragança</span><b>/</b><strong>{user.organizationName}</strong></div><label className="global-search"><Icon>⌕</Icon><input placeholder="Pesquisar em todo o sistema" onChange={event => onSearch(event.target.value)} /><kbd>⌘ K</kbd></label><div className="top-actions"><button className="top-icon">?</button><button className="top-icon has-dot">♧</button><div className="user"><div className="avatar">{user.name.split(' ').map(value => value[0]).slice(0, 2).join('')}</div><div><strong>{user.name}</strong><span>Administrador paroquial</span></div></div></div></header> }
function StatCard({ label, value, meta, tone = 'blue', icon }) { return <article className={`stat-card ${tone}`}><div className="stat-head"><span>{label}</span><span className="stat-icon">{icon}</span></div><strong>{value}</strong><small>{meta}</small></article> }
function Dashboard({ data, onNew }) { const metrics = data?.metrics || {}; return <><section className="welcome"><div><p className="eyebrow">QUINTA-FEIRA, 20 DE AGOSTO DE 2026</p><h1>Bom dia.</h1><p>Acompanhe o movimento da sua paróquia e mantenha cada cuidado em dia.</p></div><button className="primary" onClick={() => onNew('finance')}>＋ Novo lançamento</button></section><div className="filter-row"><button className="filter-select">Paróquia Santa Luzia <span>⌄</span></button><button className="filter-select">Todas as comunidades <span>⌄</span></button><span className="sync">● Dados do PostgreSQL local</span></div><div className="stat-grid"><StatCard label="Fiéis cadastrados" value={metrics.people || 0} meta="cadastros ativos" tone="blue" icon="◉" /><StatCard label="Dízimos e ofertas" value={money(metrics.tithe)} meta={`${metrics.titheCount || 0} recebimentos`} tone="gold" icon="◌" /><StatCard label="Entradas" value={money(metrics.income)} meta="movimentação acumulada" tone="green" icon="₿" /><StatCard label="Saídas" value={money(metrics.expenses)} meta="lançamentos de despesa" tone="terra" icon="↗" /></div><div className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">AUDITORIA FINANCEIRA</span><h3>Últimos lançamentos</h3></div></div><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Data</th><th>Valor</th></tr></thead><tbody>{(data?.recent || []).map(row => <tr key={row.id}><td><strong>{row.description}</strong>{row.person_name && <small className="table-sub"> · {row.person_name}</small>}</td><td>{row.category}</td><td>{new Date(row.occurred_at).toLocaleDateString('pt-BR')}</td><td className={row.kind === 'income' ? 'positive' : ''}>{money(row.amount)}</td></tr>)}</tbody></table></div></> }

function Modal({ title, children, onClose }) { return <div className="modal-backdrop"><div className="modal-card"><div className="modal-heading"><div><span className="eyebrow">NOVO REGISTRO</span><h2>{title}</h2></div><button className="close-btn" onClick={onClose}>×</button></div>{children}</div></div> }
function PeoplePage({ onDone }) { const [people, setPeople] = useState([]); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const load = () => api(`/people?search=${encodeURIComponent(query)}`).then(data => setPeople(data.data)).catch(err => setError(err.message)); useEffect(() => { load() }, [query]); const save = async event => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await api('/people', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); setOpen(false); formElement.reset(); await load(); onDone?.() } catch (err) { setError(err.message) } }; return <ModuleFrame module="Fiéis e Cadastros" title="Cadastro de fiéis" onNew={() => setOpen(true)} toolbar={<label className="table-search"><Icon>⌕</Icon><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Pesquisar registros" /></label>}><div className="panel table-panel"><div className="table-summary"><span>{people.length} registros exibidos</span><span>{error || 'Fonte: PostgreSQL local'}</span></div><table><thead><tr><th>Nome completo</th><th>Documento</th><th>Contato</th><th>Status</th></tr></thead><tbody>{people.map(person => <tr key={person.id}><td><div className="person-cell"><div className="mini-avatar">{person.name.split(' ').map(value => value[0]).slice(0, 2).join('')}</div><strong>{person.name}</strong></div></td><td>{person.document || '—'}</td><td>{person.phone || person.email || '—'}</td><td><span className="status active">Ativo</span></td></tr>)}</tbody></table></div>{open && <Modal title="Cadastrar fiel" onClose={() => setOpen(false)}><form className="record-form" onSubmit={save}><label>Nome completo<input name="name" required placeholder="Ex.: Maria Aparecida Silva" /></label><div className="form-grid"><label>Documento<input name="document" placeholder="CPF ou documento" /></label><label>Data de nascimento<input name="birthDate" type="date" /></label></div><div className="form-grid"><label>Telefone<input name="phone" /></label><label>E-mail<input name="email" type="email" /></label></div><label>Observações<textarea name="notes" rows="3" /></label><div className="modal-actions"><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="primary">Salvar fiel</button></div></form></Modal>}</ModuleFrame> }
function TithePage({ onDone }) { const [people, setPeople] = useState([]); const [open, setOpen] = useState(false); const [message, setMessage] = useState(''); useEffect(() => { api('/people').then(data => setPeople(data.data)) }, []); const save = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api('/tithe/payments', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); setMessage('Recebimento salvo e integrado ao financeiro.'); setOpen(false); onDone?.() } catch (err) { setMessage(err.message) } }; return <ModuleFrame module="Dízimos e Ofertas" title="Recebimentos" onNew={() => setOpen(true)}>{message && <div className="success-banner">{message}</div>}<div className="module-cards"><StatCard label="Recebimentos no período" value="Consultar" meta="Dízimos e ofertas" tone="gold" icon="◌" /><StatCard label="Extrato por fiel" value="Pesquisar" meta="Histórico completo" tone="blue" icon="⌕" /><StatCard label="Conciliação" value="Automática" meta="Entrada financeira integrada" tone="green" icon="✓" /></div><div className="panel module-workspace"><div><span className="eyebrow">FLUXO DE RECEBIMENTO</span><h3>Registrar dízimo ou oferta</h3><p>Escolha o fiel, informe o valor e confirme a forma de pagamento. O lançamento financeiro é criado na mesma transação.</p></div><button className="primary" onClick={() => setOpen(true)}>＋ Novo recebimento</button></div>{open && <Modal title="Lançar dízimo ou oferta" onClose={() => setOpen(false)}><form className="record-form" onSubmit={save}><label>Fiel<select name="personId" required><option value="">Selecione um fiel</option>{people.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><div className="form-grid"><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Data<input name="paymentDate" type="date" /></label></div><label>Forma de pagamento<select name="paymentMethod"><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="card">Cartão</option><option value="transfer">Transferência</option></select></label><div className="modal-actions"><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="primary">Salvar recebimento</button></div></form></Modal>}</ModuleFrame> }
function FinancePage({ onDone }) { const [open, setOpen] = useState(false); const [rows, setRows] = useState([]); useEffect(() => { api('/financial/transactions').then(data => setRows(data.data)) }, []); const save = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); await api('/financial/transactions', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); setOpen(false); const data = await api('/financial/transactions'); setRows(data.data); onDone?.() }; return <ModuleFrame module="Financeiro" title="Movimentação financeira" onNew={() => setOpen(true)}><div className="module-cards"><StatCard label="Caixa principal" value="Disponível" meta="Conta padrão" tone="green" icon="₿" /><StatCard label="Conciliação" value="Em dia" meta="Última conferência" tone="blue" icon="✓" /><StatCard label="Relatórios" value="Exportar" meta="Entradas e saídas" tone="gold" icon="↗" /></div><div className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">MOVIMENTAÇÃO</span><h3>Lançamentos recentes</h3></div><button className="primary" onClick={() => setOpen(true)}>＋ Novo lançamento</button></div><table><thead><tr><th>Descrição</th><th>Tipo</th><th>Categoria</th><th>Valor</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.description}</strong></td><td>{row.kind === 'income' ? 'Entrada' : 'Saída'}</td><td>{row.category}</td><td className={row.kind === 'income' ? 'positive' : ''}>{money(row.amount)}</td></tr>)}</tbody></table></div>{open && <Modal title="Novo lançamento financeiro" onClose={() => setOpen(false)}><form className="record-form" onSubmit={save}><label>Descrição<input name="description" required placeholder="Ex.: Compra de materiais" /></label><div className="form-grid"><label>Tipo<select name="kind"><option value="income">Entrada</option><option value="expense">Saída</option></select></label><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required /></label></div><label>Categoria<input name="category" required placeholder="Ex.: Organização religiosa" /></label><label>Data<input name="occurredAt" type="date" /></label><div className="modal-actions"><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="primary">Salvar lançamento</button></div></form></Modal>}</ModuleFrame> }
function ModuleFrame({ module, title, toolbar, onNew, children }) { const [selected, setSelected] = useState(navGroups[module]?.[0] || sectionData[module]?.tabs?.[0] || 'Resumo'); const config = sectionData[module]; const group = navGroups[module] || config?.tabs || ['Resumo', 'Cadastros', 'Relatórios', 'Configurações']; return <><section className={`module-header accent-${config?.accent || 'blue'}`}><div><span className="eyebrow">MÓDULO · {module.toUpperCase()}</span><h1>{module}</h1><p>{config?.subtitle || 'Cadastros, rotinas e relatórios integrados da sua paróquia.'}</p></div><div className="module-actions"><button className="secondary">Exportar</button>{onNew ? <button className="primary" onClick={onNew}>＋ Novo registro</button> : <span className="module-state">Estrutura em preparação</span>}</div></section><div className="module-layout"><div className="module-menu">{group.map(item => <button key={item} className={selected === item ? 'selected' : ''} onClick={() => setSelected(item)}>{item}<span>›</span></button>)}</div><div className="module-content"><div className="module-toolbar"><div><h2>{title || config?.title || selected}</h2><span>Paróquia Santa Luzia · exercício 2026</span></div><div className="toolbar-actions">{toolbar}{toolbar && <button className="secondary">Filtros <span>＋</span></button>}</div></div>{children || <ModuleOverview config={config} onNew={onNew} />}</div></div></> }
function ModuleOverview({ config, onNew }) { return <><div className="module-cards"><StatCard label={config?.fields?.[0] || 'Registros ativos'} value="—" meta="Pronto para cadastrar" tone={config?.accent || 'blue'} icon="◉" /><StatCard label={config?.fields?.[1] || 'Pendências'} value="—" meta="Acompanhar no período" tone="gold" icon="◷" /><StatCard label={config?.fields?.[2] || 'Relatórios'} value="PDF" meta="Disponível para emissão" tone="green" icon="↗" /></div><div className="panel module-workspace"><div><span className="eyebrow">ÁREA DE TRABALHO</span><h3>{config?.title || 'Configurações do módulo'}</h3><p>{config?.subtitle || 'Selecione uma rotina no menu lateral para começar.'}</p><div className="workflow-steps"><span>01 · Cadastro</span><span>02 · Acompanhamento</span><span>03 · Relatório</span></div></div><button className="primary" onClick={onNew}>＋ Começar cadastro</button></div></> }
function App() { const [user, setUser] = useState(null); const [active, setActive] = useState('Visão geral'); const [search, setSearch] = useState(''); const [dashboard, setDashboard] = useState(null); const [refresh, setRefresh] = useState(0); useEffect(() => { if (localStorage.getItem('nucleo_token')) api('/me').then(data => setUser(data.user)).catch(() => localStorage.removeItem('nucleo_token')) }, []); useEffect(() => { if (user) api('/dashboard').then(setDashboard) }, [user, refresh]); if (!user) return <Login onLogin={setUser} />; const logout = () => { localStorage.removeItem('nucleo_token'); setUser(null) }; const done = () => setRefresh(value => value + 1); return <div className="app-shell"><Sidebar active={active} onSelect={setActive} onLogout={logout} /><div className="main-shell"><Topbar user={user} onSearch={setSearch} /><main className="main-content">{search && <div className="search-banner">Pesquisando por <strong>“{search}”</strong><button onClick={() => setSearch('')}>Limpar</button></div>}{active === 'Visão geral' && <Dashboard data={dashboard} onNew={() => setActive('Financeiro')} />}{active === 'Fiéis e Cadastros' && <PeoplePage onDone={done} />}{active === 'Dízimos e Ofertas' && <TithePage onDone={done} />}{active === 'Financeiro' && <FinancePage onDone={done} />}{active !== 'Visão geral' && !['Fiéis e Cadastros', 'Dízimos e Ofertas', 'Financeiro'].includes(active) && <ModuleFrame module={active}><ModuleOverview config={sectionData[active]} onNew={() => {}} /></ModuleFrame>}</main><footer className="footer"><span>Núcleo Eclesial · Ambiente local</span><span>PostgreSQL · <a href="#auditoria">Auditoria ativa</a></span></footer></div></div> }
export default App
createRoot(document.getElementById('root')).render(<App />)
